# Generated by Django 6.0.5 on 2026-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarbonBudget",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("before_net_emission", models.FloatField(blank=True, null=True)),
                (
                    "before_net_monthly_emission",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "before_per_capita_emission",
                    models.FloatField(blank=True, null=True),
                ),
                ("before_total_emission", models.FloatField(blank=True, null=True)),
                ("after_new_net_emission", models.FloatField(blank=True, null=True)),
                (
                    "after_previous_net_emission",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "after_total_emission_reduction",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "after_total_impact_reduction_plus_sequestration",
                    models.FloatField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "carbon_budget",
            },
        ),
        migrations.CreateModel(
            name="Emissions",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("agriculture_rice_kharif", models.FloatField(blank=True, null=True)),
                ("agriculture_wheat_rabi", models.FloatField(blank=True, null=True)),
                ("energy_electricity", models.FloatField(blank=True, null=True)),
                ("residential_firewood", models.FloatField(blank=True, null=True)),
                ("residential_lpg", models.FloatField(blank=True, null=True)),
                ("transport_petrol_vehicles", models.FloatField(blank=True, null=True)),
                ("waste_solid_waste", models.FloatField(blank=True, null=True)),
                (
                    "livestock_enteric_fermentation",
                    models.FloatField(blank=True, null=True),
                ),
                ("waste_solid_waste_2", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "emissions",
            },
        ),
        migrations.CreateModel(
            name="Interventions",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "cooking_lpg_efficiency_10pct",
                    models.FloatField(blank=True, null=True),
                ),
                ("energy_solar_rooftop_500m", models.FloatField(blank=True, null=True)),
                (
                    "transport_ev_adoption_20pct",
                    models.FloatField(blank=True, null=True),
                ),
                ("composting_pit_20pct", models.FloatField(blank=True, null=True)),
                (
                    "biomass_improved_cookstove_10pct",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "agriculture_rice_methane_reduction_15pct",
                    models.FloatField(blank=True, null=True),
                ),
                ("solid_waste_solid", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "interventions",
            },
        ),
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("total_population", models.FloatField(blank=True, null=True)),
                ("total_area_ha", models.FloatField(blank=True, null=True)),
                ("builtup_area_ha", models.FloatField(blank=True, null=True)),
                ("agricultural_area_ha", models.FloatField(blank=True, null=True)),
                ("water_bodies_area_ha", models.FloatField(blank=True, null=True)),
                ("total_households", models.FloatField(blank=True, null=True)),
                ("total_livestock", models.FloatField(blank=True, null=True)),
                ("total_vehicles", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "overview",
            },
        ),
        migrations.CreateModel(
            name="Scenarios",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("bau_2023", models.FloatField(blank=True, null=True)),
                ("bau_2025", models.FloatField(blank=True, null=True)),
                ("bau_2030", models.FloatField(blank=True, null=True)),
                ("bau_2035", models.FloatField(blank=True, null=True)),
                ("los_2023", models.FloatField(blank=True, null=True)),
                ("los_2025", models.FloatField(blank=True, null=True)),
                ("los_2030", models.FloatField(blank=True, null=True)),
                ("los_2035", models.FloatField(blank=True, null=True)),
                ("acc_2023", models.FloatField(blank=True, null=True)),
                ("acc_2025", models.FloatField(blank=True, null=True)),
                ("acc_2030", models.FloatField(blank=True, null=True)),
                ("acc_2035", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "scenarios",
            },
        ),
        migrations.CreateModel(
            name="Sequestration",
            fields=[
                (
                    "vlcode",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "before_total_sequestration",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "after_total_sequestration_increase",
                    models.FloatField(blank=True, null=True),
                ),
                ("before_forest", models.FloatField(blank=True, null=True)),
                ("after_plantation", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "sequestration",
            },
        ),
    ]
