# Generated by Codex on 2026-05-13

from django.conf import settings
from django.db import migrations, models


def copy_staff_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminUser = apps.get_model("carbon_api", "AdminUser")
    for user in User.objects.filter(is_staff=True):
        AdminUser.objects.get_or_create(
            username=user.username,
            defaults={
                "password": user.password,
                "email": user.email or "",
                "is_active": user.is_active,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carbon_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_users",
            },
        ),
        migrations.RunPython(copy_staff_users, migrations.RunPython.noop),
    ]
